### PR TITLE
Update prometheus

### PR DESCRIPTION
**Pull request by harry671003**
### Changes
- This PR updates the  prometheus to https://github.com/prometheus/prometheus/commit/65f610353919
- This is the initial PR that addresses the following breaking changes:
  - https://github.com/prometheus/prometheus/pull/13904 - make lookback and matrix selections left-open and right-closed
  - https://github.com/prometheus/prometheus/pull/14677 - Exponential interpolation
  - https://github.com/prometheus/prometheus/pull/14413 - Kahan summation changes
  - https://github.com/prometheus/prometheus/pull/14655 - Fall back to full label sets when sorting by label
  - https://github.com/prometheus/prometheus/pull/14821 - Correctly handle unary negation

- Tests are expected to fail because the following breaking (and possibly other)  are not addressed yet.
  - https://github.com/prometheus/prometheus/pull/14477 - Delayed name dropping
  - https://github.com/prometheus/prometheus/pull/14688 - Moved the native histogram binary operation tests into acceptance tests.
  - https://github.com/prometheus/prometheus/pull/14611 and more - Added annotations to native histogram

### Note
- The PR is made against a separate branch [prometheus-update-65f610353919](https://github.com/thanos-io/promql-engine/tree/prometheus-update-65f610353919) to co-ordinate the work.

### CODE REVIEW

**Comment by GiedriusS** [comment]
I think it won't be so easy due to https://github.com/thanos-io/promql-engine/issues/486.

**Comment by fpetkovski** [comment]
I do not understand the new behavior, raised an issue here: https://github.com/prometheus/prometheus/issues/14961.

**Comment by yeya24** [comment]
Quite a lot of tests failed due to round. Should we add my fix to `round` function to see how much it would help?

```
--- FAIL: TestInstantQuery/round/disableOptimizers=false/disableFallback=true#04 (0.00s)
                testutil.go:91: engine_test.go:4215: "Query: round(http_requests_total)
                    Explanation:
                    [duplicateLabelCheck]:
                    └──[function] round([http_requests_total]):
                       └──[coalesce]:
                          ├──[concurrent(buff=2)]:
                          │  └──[vectorSelector] {[__name__="http_requests_total"]} 0 mod 2
                          └──[concurrent(buff=2)]:
                             └──[vectorSelector] {[__name__="http_requests_total"]} 1 mod 2
                    
                    "
                    
                    	exp: &promql.Result{Err:error(nil), Value:promql.Vector{promql.Sample{T:0, F:1, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"__name__", Value:"http_requests_total"}, labels.Label{Name:"pod", Value:"nginx-1"}, labels.Label{Name:"series", Value:"1"}}, DropName:true}, promql.Sample{T:0, F:2, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"__name__", Value:"http_requests_total"}, labels.Label{Name:"pod", Value:"nginx-2"}, labels.Label{Name:"series", Value:"2"}}, DropName:true}, promql.Sample{T:0, F:5, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"__name__", Value:"http_requests_total"}, labels.Label{Name:"pod", Value:"nginx-4"}, labels.Label{Name:"series", Value:"3"}}, DropName:true}, promql.Sample{T:0, F:8, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"__name__", Value:"http_requests_total"}, labels.Label{Name:"pod", Value:"nginx-5"}, labels.Label{Name:"series", Value:"1"}}, D...(output trimmed)
                    
                    	got: &promql.Result{Err:error(nil), Value:promql.Vector{promql.Sample{T:0, F:1, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"pod", Value:"nginx-1"}, labels.Label{Name:"series", Value:"1"}}, DropName:false}, promql.Sample{T:0, F:2, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"pod", Value:"nginx-2"}, labels.Label{Name:"series", Value:"2"}}, DropName:false}, promql.Sample{T:0, F:5, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"pod", Value:"nginx-4"}, labels.Label{Name:"series", Value:"3"}}, DropName:false}, promql.Sample{T:0, F:8, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"pod", Value:"nginx-5"}, labels.Label{Name:"series", Value:"1"}}, DropName:false}, promql.Sample{T:0, F:2, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"pod", Value:"nginx-6"}, labels.Label{Name:"series", Value:"2"}}, DropName:false}}, Warnings:annotations.Annotations{}}
                    
                    Diff:
                    --- Expected
                    +++ Actual
                    @@ -1,6 +1,6 @@
                    -(*promql.Result)({__name__="http_requests_total", pod="nginx-1", series="1"} => 1 @[0]
                    -{__name__="http_requests_total", pod="nginx-2", series="2"} => 2 @[0]
                    -{__name__="http_requests_total", pod="nginx-4", series="3"} => 5 @[0]
                    -{__name__="http_requests_total", pod="nginx-5", series="1"} => 8 @[0]
                    -{__name__="http_requests_total", pod="nginx-6", series="2"} => 2 @[0])
                    +(*promql.Result)({pod="nginx-1", series="1"} => 1 @[0]
                    +{pod="nginx-2", series="2"} => 2 @[0]
                    +{pod="nginx-4", series="3"} => 5 @[0]
                    +{pod="nginx-5", series="1"} => 8 @[0]
                    +{pod="nginx-6", series="2"} => 2 @[0])
```

**Comment by MichaHoffmann** [comment]
> Quite a lot of tests failed due to round. Should we add my fix to `round` function to see how much it would help?
> 
> ```
> --- FAIL: TestInstantQuery/round/disableOptimizers=false/disableFallback=true#04 (0.00s)
>                 testutil.go:91: engine_test.go:4215: "Query: round(http_requests_total)
>                     Explanation:
>                     [duplicateLabelCheck]:
>                     └──[function] round([http_requests_total]):
>                        └──[coalesce]:
>                           ├──[concurrent(buff=2)]:
>                           │  └──[vectorSelector] {[__name__="http_requests_total"]} 0 mod 2
>                           └──[concurrent(buff=2)]:
>                              └──[vectorSelector] {[__name__="http_requests_total"]} 1 mod 2
>                     
>                     "
>                     
>                     	exp: &promql.Result{Err:error(nil), Value:promql.Vector{promql.Sample{T:0, F:1, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"__name__", Value:"http_requests_total"}, labels.Label{Name:"pod", Value:"nginx-1"}, labels.Label{Name:"series", Value:"1"}}, DropName:true}, promql.Sample{T:0, F:2, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"__name__", Value:"http_requests_total"}, labels.Label{Name:"pod", Value:"nginx-2"}, labels.Label{Name:"series", Value:"2"}}, DropName:true}, promql.Sample{T:0, F:5, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"__name__", Value:"http_requests_total"}, labels.Label{Name:"pod", Value:"nginx-4"}, labels.Label{Name:"series", Value:"3"}}, DropName:true}, promql.Sample{T:0, F:8, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"__name__", Value:"http_requests_total"}, labels.Label{Name:"pod", Value:"nginx-5"}, labels.Label{Name:"series", Value:"1"}}, D...(output trimmed)
>                     
>                     	got: &promql.Result{Err:error(nil), Value:promql.Vector{promql.Sample{T:0, F:1, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"pod", Value:"nginx-1"}, labels.Label{Name:"series", Value:"1"}}, DropName:false}, promql.Sample{T:0, F:2, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"pod", Value:"nginx-2"}, labels.Label{Name:"series", Value:"2"}}, DropName:false}, promql.Sample{T:0, F:5, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"pod", Value:"nginx-4"}, labels.Label{Name:"series", Value:"3"}}, DropName:false}, promql.Sample{T:0, F:8, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"pod", Value:"nginx-5"}, labels.Label{Name:"series", Value:"1"}}, DropName:false}, promql.Sample{T:0, F:2, H:(*histogram.FloatHistogram)(nil), Metric:labels.Labels{labels.Label{Name:"pod", Value:"nginx-6"}, labels.Label{Name:"series", Value:"2"}}, DropName:false}}, Warnings:annotations.Annotations{}}
>                     
>                     Diff:
>                     --- Expected
>                     +++ Actual
>                     @@ -1,6 +1,6 @@
>                     -(*promql.Result)({__name__="http_requests_total", pod="nginx-1", series="1"} => 1 @[0]
>                     -{__name__="http_requests_total", pod="nginx-2", series="2"} => 2 @[0]
>                     -{__name__="http_requests_total", pod="nginx-4", series="3"} => 5 @[0]
>                     -{__name__="http_requests_total", pod="nginx-5", series="1"} => 8 @[0]
>                     -{__name__="http_requests_total", pod="nginx-6", series="2"} => 2 @[0])
>                     +(*promql.Result)({pod="nginx-1", series="1"} => 1 @[0]
>                     +{pod="nginx-2", series="2"} => 2 @[0]
>                     +{pod="nginx-4", series="3"} => 5 @[0]
>                     +{pod="nginx-5", series="1"} => 8 @[0]
>                     +{pod="nginx-6", series="2"} => 2 @[0])
> ```

It feels like the issue is on prometheus side, we should bump prometheus to include your fix i think.

**Comment by yeya24** [comment]
@fpetkovski @MichaHoffmann Can you please take a look at the PR?
I reviewed most of the code changes other than code relevant to https://github.com/prometheus/prometheus/pull/14413.

**Comment by yeya24** [comment]
Let's get this PR merged as it targets a non main branch. We can iterate on top of it

**Comment by fpetkovski** [comment]
Sorry missed this notification. Merging against a non-main branch makes perfect sense 👍

**Pull request merged**
