### PR TITLE
upgrade Prometheus version to latest main

### PR DESCRIPTION
**Pull request by yeya24**
Upgrade Prometheus version to latest main to unblock upgrading prometheus version in Thanos main repo.

### CODE REVIEW

**Review by fpetkovski — APPROVED** [review]

**Comment by fpetkovski** [comment]
Looks like we might need to bump the go version.

**Comment by yeya24** [comment]
Something seems wrong for this version upgrade. I don't think it is an issue on us. Maybe upstream changed something?

```
--- FAIL: FuzzEnginePromQLSmithInstantQuery (0.88s)
    --- FAIL: FuzzEnginePromQLSmithInstantQuery (0.23s)
        enginefuzz_test.go:449: load 30s
            			http_requests_total{pod="nginx-1", route="/"} 600.00+10.00x40
            			http_requests_total{pod="nginx-2", route="/"}  8+28.00x40
        enginefuzz_test.go:451: increase({__name__="http_requests_total",route="/"} offset 1m7s[1h:1m] offset -3m33s)
        enginefuzz_test.go:453: case 71 error mismatch.
            new result: {pod="nginx-1", route="/"} => 55.666666666666664 @[44000]
            {pod="nginx-2", route="/"} => 163.86666666666667 @[44000]
            old result: {pod="nginx-1", route="/"} => 55.666666666666664 @[44000]
            {pod="nginx-2", route="/"} => 155.86666666666667 @[44000]
        enginefuzz_test.go:458: failed 1 test cases
```

**Comment by MichaHoffmann** [comment]
Probably something around rate and increase changed in upstream?

**Comment by GiedriusS** [comment]
https://github.com/prometheus/prometheus/pull/13725 maybe this one?

**Pull request merged**
